### ISSUE TITLE
有时候chunk边界会在某些区域异常显示

### ISSUE THREAD

**Issue by Milvona** [hhhxiao/trapdoor-ll#101]
### trapdoor版本

trapdoor-0.38.0-1.19.81.01-e3b1ca0

### LiteLoaderBDS版本

LiteLoaderBDS 2.13.1+13d598e

### BDS版本

Version 1.19.81.01(ProtocolVersion 582)

### 发生了什么?

某些区块会没人异常显示边界

**Comment by hhhxiao** [comment]
请在修改 "当前版本" 为具体的版本号

**Comment by hhhxiao** [comment]
没发现bug，暂时关了，如果还有其他人反馈再打开
