### ISSUE TITLE
假人无法把背包内物品切换至主手

### ISSUE THREAD

**Issue by tof114514** [hhhxiao/trapdoor-ll#104]
### trapdoor版本

trapdoor-ll-0.38.0-1.20.0.01

### LiteLoaderBDS版本

2.14.1

### BDS版本

1.20.01

### 发生了什么?

假人无法通过select指令选择背包内物品
且set指令不存在 无法执行

### 复现此问题的步骤

输入指令即可

**Comment by hhhxiao** [comment]
#105
