### ISSUE TITLE
有关1.20+所有假人相关的问题请在这里集中提出

### ISSUE THREAD

**Issue by hhhxiao** [hhhxiao/trapdoor-ll#105]
1.20更新后假人的部分API出现问题，或者失效，或者动画不渲染等等，如果你发现问题请在这里集中反馈

**Comment by hhhxiao** [comment]
目前已知的问题：
 - `select`选择物品后渲染不更新 (#104 )
 - `use`命令使用物品失效

**Comment by hhhxiao** [comment]
#105

**Comment by XianYuFDK** [comment]
非管理无法使用假人？

**Comment by hhhxiao** [comment]
> 非管理无法使用假人？

改配置文件，具体看wiki

**Comment by Townrain** [comment]
我和朋友运雪狐，然后他挂个假人在活塞虫上面就下线了，我过会上线用指令查了查到哪了，然后发现假人坐标没有发生改变，等他找到活塞虫时，假人又突然出现
![Cache_7f39c92befc220b0](https://github.com/bedrock-dev/trapdoor-ll/assets/95573719/e43cd87e-ead4-46b5-9d4f-d007a18a81eb)
![Uploading Screenshot_2023-07-27-18-28-08-90.jpg…]()

**Comment by Townrain** [comment]
![Uploading Screenshot_2023-07-27-18-28-08-90.jpg…]()

**Comment by Townrain** [comment]
![Screenshot_2023-07-27-18-28-08-90](https://github.com/bedrock-dev/trapdoor-ll/assets/95573719/1adb116a-9452-4316-922f-e9f1c942263b)

**Comment by zxcier9658** [comment]
假人退出會導致伺服器崩潰

**Comment by zxcier9658** [comment]
問題已解決
假人會跟顯示血量的模組有衝突
模組名稱：（AxisHealthBar)V1.01
