### ISSUE TITLE
无法显示可视化内容 如村庄边界

### ISSUE THREAD

**Issue by muyouyyds** [hhhxiao/trapdoor-ll#106]
### trapdoor版本

0.38.0-1.20.0.01

### LiteLoaderBDS版本

2.14.1

### BDS版本

bedrock-server-1.20.1.02

### 发生了什么?

trapdoor正常安装 可以使用大部分功能 但是无法显示史莱姆区块 无法显示村庄中心 无法显示村庄边界 可显示文字性内容 如村民信息/village head 等
材质包已装 /func /self中相关功能都已开启
怀疑是材质包的问题？

**Comment by hhhxiao** [comment]
99%资源包装错了，认真看wiki再试试

**Comment by yufengya0420** [comment]
我也出现了同样的问题，服务端和客户端都装了资源包，但是不显示

**Comment by hhhxiao** [comment]
测试没问题，请查看wiki检查资源版是否安装正确
