### ISSUE TITLE
Enhancement : 假人随着服务端启动自启

### ISSUE THREAD

**Issue by railgun19982** [hhhxiao/trapdoor-ll#107]
### 您的建议是否与现存的某个问题相关?请描述问题?

——What happened?——
更新完1.20版本的BDS之后，服务端的上玩家活跃程度相同的情况下，性能开销会随着服务端连续运行的时间不断增大，最后到达处理器性能瓶颈，导致非正常的TPS降低。
此问题稍后会反馈到Jira，但为了保证玩家的体验，我在守护进程中添加了规则：每日凌晨四点发出stop服务器的指令，在得到成功关闭服务器的返回信息服务器后再次启动服务器。
但每次重启之后，假人将会重置，为服务器带来了一定麻烦。
——Band-aid solution——
管理每天早起去挂假人

### 您认为还缺少什么?如何解决您的问题?

创建假人的时候可以选择将假人的基本信息持久化在本地硬盘，服务器重启的时候可以根据持久化内容与相关配置文件内容选择性恢复重启前假人的位置与状态。

**Comment by hhhxiao** [comment]
这个功能是有的，但是由于BDS的bug被我暂时禁用了，原因在于在未加载的区块生成的假人无法正常加载区块，而且这问题一直没有修复，因此暂时不开放。详见 https://github.com/bedrock-dev/trapdoor-ll/issues/23
