### ISSUE TITLE
/log os命令得到的CPU Total  Usage数字不正确

### ISSUE THREAD

**Issue by Singl-Daemon** [hhhxiao/trapdoor-ll#11]
### trapdoor版本号版本

0.16-1.19.10.03

### LiteLoader版本

2.4.2

### BDS版本

1.19.11

### 发生了什么?

执行/log os得到的一些数字不正确
![a](https://user-images.githubusercontent.com/33011851/183370127-1bbca86c-4d44-4276-8f8b-0ad28f949afa.jpg)

### 复现此问题的步骤

1:安装trapdoor
2:/log os

**Comment by hhhxiao** [comment]
能提供一些系统信息吗
比如Windows版本，cpu型号，是不是虚拟机环境 有没有用wine等等

**Comment by hhhxiao** [comment]
不会修，目前的方案是数据出现异常就显示`Unknown`,反正先这样吧，这个issue先不关了，说不定有个大佬看到了就整个pr

**Comment by Singl-Daemon** [comment]
> 能提供一些系统信息吗 比如Windows版本，cpu型号，是不是虚拟机环境 有没有用wine等等

Windows教育版 21H1 12th Gen Intel(R) Core(TM) i9-12900K VMware虚拟机

**Comment by acm233** [comment]
> 能提供一些系统信息吗 比如Windows版本，cpu型号，是不是虚拟机环境 有没有用wine等等

Windows教育版 21H1 12th Gen Intel(R) Core(TM) i9-12900K VMware虚拟机
