### ISSUE TITLE
希望假人再次上线时，是在上一次假人离线的位置

### ISSUE THREAD

**Issue by yuanxi953** [hhhxiao/trapdoor-ll#110]
### 您的建议是否与现存的某个问题相关?请描述问题?

例如我使用/player test spawn在当前位置上线一个名为test的假人，然后再使用/player test despawn让其下线，我换到另一个位置再次上线它，希望它这次上线的位置是在上次下线的位置，而不再是在命令执行者的位置

### 您认为还缺少什么?如何解决您的问题?

这是希望增加的一个新功能

**Comment by hhhxiao** [comment]
如果直接生成在非加载区块上假人会因为bug无法加载区块，因此这个功能只有这个区块加载bug修了才考虑添加

**Comment by hhhxiao** [comment]
详见 #23
