### ISSUE TITLE
仙人掌无法正常旋转某些红石原件

### ISSUE THREAD

**Issue by yuanxi953** [hhhxiao/trapdoor-ll#111]
### trapdoor版本

0.39.0-1.20.0.01

### LiteLoaderBDS版本

2.14.1

### BDS版本

1.20.1.02

### 发生了什么?

仙人掌无法正常旋转类似于比较器、中继器等红石原件，一般表现为旋转了一次之后就无法再次旋转

### 复现此问题的步骤

1、手持仙人掌
2、控制台或OP发送 func blockrotate true
3、个人发送/self blockrotate true
4、第一次右击中继器or比较器，正常旋转
5、第二次右击中继器or比较器，无法旋转
n、测试其他方块正常

**Comment by quizhizhe** [comment]
已定位问题，会在发布适配BDS1.20.11.01的版本时修复
