### ISSUE TITLE
有关暂时停更的声明

### ISSUE THREAD

**Issue by hhhxiao** [hhhxiao/trapdoor-ll#113]
最近开发者私事太多，因此暂时停更半个月到一个月。不过还是会接受PR

**Comment by baixiong2530** [comment]
啊？我还想着最近在1.20.11上使用。现在只能作罢了。
虽然有些遗憾，但是还是希望作者去多休息为我们带来更好的体验。

**Comment by railgun19982** [comment]
辛苦
