### ISSUE TITLE
开服报错无法加载

### ISSUE THREAD

**Issue by yufengoh** [hhhxiao/trapdoor-ll#118]
### trapdoor版本

0.38.0-1.20.0.01

### LiteLoaderBDS版本

2.15.0

### BDS版本

1.20.15

### 发生了什么?

17:51:47 ERROR [LiteLoader] Fail to load plugin <trapdoor-0.38.0-1.20.0.01-34ad47e.dll>!
17:51:47 ERROR [LiteLoader] Error: Code[127] 找不到指定的程序。

### 复现此问题的步骤

开服

**Comment by hhhxiao** [comment]
版本不对
