### ISSUE TITLE
生成假人后再把假人杀了或移除就崩服

### ISSUE THREAD

**Issue by yufengoh** [hhhxiao/trapdoor-ll#119]
### trapdoor版本

trapdoor-ll-0.40.0-1.20.11.01

### LiteLoaderBDS版本

2.15.0

### BDS版本

1.20.15

### 发生了什么?

[minidump_2023-09-02_11-21-57.zip](https://github.com/bedrock-dev/trapdoor-ll/files/12503078/minidump_2023-09-02_11-21-57.zip)
生成假人后再把假人杀了或移除就崩服

### 复现此问题的步骤

生成假人后再把假人杀了或移除就崩服

**Comment by zxcier9658** [comment]
我也有遇到一樣的問題，把伺服器一些模組移除假人退出之後就不會崩服了

**Comment by yufengoh** [comment]
我初步排查了下装了PBLP插件并开启了其中的功能再使用假人时会崩服，我看不了崩服文件求作者解决！

**Comment by hhhxiao** [comment]
我不知道PBLP是什么，tr不保证和其他插件的兼容性
