### ISSUE TITLE
假人背包数据写入错误

### ISSUE THREAD

**Issue by huxian28** [hhhxiao/trapdoor-ll#12]
### trapdoor version

trapdoor-0.16-1.19.10.03

### LiteLoader version

2.4.2

### BDS version

1.19.11

### What happened?

![D0ARXBXV8T0% ZL8 ~}8N$B](https://user-images.githubusercontent.com/92313858/183294477-53a62bad-c6f4-4958-bc21-70d1d99a2dde.png)
![WJ`}{}_HYDQIMN2B~P81OYP](https://user-images.githubusercontent.com/92313858/183294479-5c90bbfc-90b2-4e10-8833-5b0828a74b67.png)

假人可以正常操作，但服务器找不到假人背包数据，后台一直报错

### Steps to reproduce

无

**Comment by imyeeyee1** [comment]
我也是这样

**Comment by hhhxiao** [comment]
> 我也是这样

去配置文件把背包存储关了，就是`keep-sim-inv`这个选项改成`false`

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll/commit/7875152c79af1850c53949ebcd442d23b1414a1c
应该修了

**Comment by imyeeyee1** [comment]
> [7875152](https://github.com/hhhxiao/trapdoor-ll/commit/7875152c79af1850c53949ebcd442d23b1414a1c) 应该修了

没问题了

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll/releases/tag/0.17.5-1.19.20.02
