### ISSUE TITLE
假人生成造成崩服问题

### ISSUE THREAD

**Issue by crowdedplus** [hhhxiao/trapdoor-ll#120]
### trapdoor版本

0.41.0

### LiteLoaderBDS版本

2.16.0

### BDS版本

1.20.30.02

### 发生了什么?

命令/player a spawn 之后崩服。
[minidump_2023-09-30_10-54-41.zip](https://github.com/bedrock-dev/trapdoor-ll/files/12773499/minidump_2023-09-30_10-54-41.zip)

**Comment by hhhxiao** [comment]
用2.16.1或者2.16.2
