### ISSUE TITLE
漏斗计数器除了白色0通道其他的都用不了

### ISSUE THREAD

**Issue by Daisy-AC17** [hhhxiao/trapdoor-ll#121]
### trapdoor版本

trapdoor-0.39.0-1.20.0.01-18ae2e0

### LiteLoaderBDS版本

LiteLoaderBDS 2.15.0+50eb265

### BDS版本

1.20.15

### 发生了什么?

漏斗计数器除了白色0通道都用不了，混凝土命名改了

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/pull/122
