### ISSUE TITLE
Liteloader改名为LeviLamina导致安装器不认

### ISSUE THREAD

**Issue by TC999** [hhhxiao/trapdoor-ll#124]
### trapdoor版本

0.42.1-1.20.30.02

### LiteLoaderBDS版本

v0.4.2

### BDS版本

1.20.30.02

### 发生了什么?

LiteLoader不知道什么时候改名为[**LeviLamina**](https://github.com/LiteLDev/LeviLamina)，导致安装后安装器不识别

- 注：在实际操作中，将`LeviLamina.dll`改名为`LiteLoader.dll`即可解决

**Comment by hhhxiao** [comment]
tr暂不支持levilamina，建议等更新
