### ISSUE TITLE
Wonderful adaption｜望作者适配levilamina(适用于1.20.51的新liteloaderbds加载器)

### ISSUE THREAD

**Issue by superwfox** [hhhxiao/trapdoor-ll#125]
### 您的建议是否与现存的某个问题相关?请描述问题?

冬去春来，新年已到 预祝作者新的一年龙蟠虎踞 前途无限！
Trapdoor作为一款功能强大的全能型辅助工具在服务器圈内名声大噪 用户颇多。
近期liteloaderbds焕然一新 迎i来levilamina加载器 更轻量 性能强大许多 不知作者可否能抽出宝贵的时间更新trapdoor插件以适配levilamina加载器 1.20.51新鲜玩法许多 对于我们这些腐竹吸引力很强 对trapdoor更新的诉求着实真切 往作者更新以报

### 您认为还缺少什么?如何解决您的问题?

倘若trapdoor可以导出建筑为mcstructure就圆满了

**Comment by hhhxiao** [comment]
LL2 -> levilamina 改动太大了，工作量过大，短期内基本没戏，长期只能看运气了，细节见https://github.com/bedrock-dev/trapdoor-ll/issues/127
