### ISSUE TITLE
假人挂刷铁机没效果，不刷铁傀儡

### ISSUE THREAD

**Issue by XCLHove** [hhhxiao/trapdoor-ll#14]
### trapdoor版本号版本

0.17-1.19.20

### LiteLoader版本

2.5.0

### BDS版本

1.19.20

### 发生了什么?

用假人挂刷铁机不刷铁傀儡

### 复现此问题的步骤

用假人挂刷铁机不刷铁傀儡

**Comment by hhhxiao** [comment]
你确定不是你刷铁机造的有问题？

**Comment by XCLHove** [comment]
> 你不是确定你刷铁机造的有问题吗？

哥呀，我用ddf1897的fakeplayer都挂了几大箱子了，今天刚更1.19.20用不了fakeplayer才用trapdoor的假人挂，我自己开本地服务器研究刷铁机也遇到过这样的问题，我在别的服务器玩的时候也遇到这样的问题，真人挂机刷铁机没问题，用假人就是不刷

**Comment by hhhxiao** [comment]
OK,我有空研究下

**Comment by hhhxiao** [comment]
只有假人的情况下有村庄更新吗，就你和假人离得非常远，假人挂刷帖机，你在很远的地方用`/village list`看看有输出吗

**Comment by hhhxiao** [comment]
我这边假人能正常加载村庄，bug无法复现

**Comment by hhhxiao** [comment]
有可能和 #23 有关，这边先关闭了，等我修好那边的bug再看看能不能复现
