### ISSUE TITLE
mctick.cpp

### ISSUE THREAD

**Issue by Chlna6666** [hhhxiao/trapdoor-ll#16]
### trapdoor版本号版本

0.17

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

崩溃啦
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function CircuitSystem::updateBlocks at 0x7FF617DCEE50  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617DCEF57  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function LevelChunk::tick at 0x7FF617CC78B0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617CC815A  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::original<LevelChunk * &,void * &,void * &> at 0x7FFAF21892A0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 275 
[StackTrace] Function ???????? at 0x7FFAF218930A  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::_hook at 0x7FFAF21878F0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 290 
[StackTrace] Function ???????? at 0x7FFAF2187AB4  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActor at 0x7FF616D08890  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616D0894E  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActorView at 0x7FF616D08B80  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616D08C65  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ??$each@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@@@Z$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$type_list@$$V@entt@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@EntityRegistryBase@@QEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@@@Z@Z at 0x7FF616D08060  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616D08223  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function LevelChunkTickingSystem::tick at 0x7FF616D092D0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616D092EA  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_32d13dfb866b2b1150b222173a507f00>,void,ITickingSystem &,TickingSystemId>::_Do_call at 0x7FF616C0C7C0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616C0C7D9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF617037EF0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617038217  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function EntitySystems::tick at 0x7FF616C0D060  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF616C0D103  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::original<void * &,void * &> at 0x7FFAF21894C0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 343 
[StackTrace] Function ???????? at 0x7FFAF218950E  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::_hook at 0x7FFAF2187FB0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 353 
[StackTrace] Function ???????? at 0x7FFAF2188092  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function <lambda_b44508b61f37969cf480280e06e54415>::operator() at 0x7FF617A4E290  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A4E3E4  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Level::tickEntitySystems at 0x7FF617A62E40  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A62E7A  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Level::tick at 0x7FF617A61F30  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A62408  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerLevel::tick at 0x7FF6172CF0A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6172CF0E9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFAF2189110  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFAF2189142  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFAF21874A0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFAF2187512  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function ???????? at 0x7FFAE5F529B1  [LiteLoader.Js.dll<2.5.1.2665>]
[StackTrace] Function ???????? at 0x7FFAE4EB7E05  [LiteLoader.Lua.dll<2.5.1.2665>]
[StackTrace] Function Schedule::nextTick at 0x7FFAEB1B13A0  [LiteLoader.dll<2.5.1.2665>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAEB1B15AA  [LiteLoader.dll<2.5.1.2665>]
[StackTrace] Function GameSession::tick at 0x7FF6173CB680  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6173CB6B8  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Minecraft::update at 0x7FF6170BC130  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170BCB90  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerInstance::_update at 0x7FF6170D8240  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D833D  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF6170D6820  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D6C92  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF6170D3B80  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D3B8E  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function o_exp at 0x7FFB14A52630  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A5268A  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFB16E97960  [KERNEL32.DLL<6.2.17763.3287>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB16E97974  [KERNEL32.DLL<6.2.17763.3287>]
[StackTrace] Function RtlUserThreadStart at 0x7FFB1795A2D0  [ntdll.dll<6.2.17763.3232>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB1795A2F1  [ntdll.dll<6.2.17763.3232>]

### 复现此问题的步骤

已经出现三次
我也不知道是怎么触发的

**Comment by Chlna6666** [comment]
第二次
[StackTrace] Function invoke_watson at 0x7FFB14A9D270  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A9D288  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFB14A9D240  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A9D25E  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function std::vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > >::~vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > > at 0x7FF61689E790  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF61689E80A  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::_Hash<std::_Umap_traits<SubChunkPos,UpdateSubChunkBlocksPacket::BlocksChangedInfo,std::_Uhash_compare<SubChunkPos,std::hash<SubChunkPos>,std::equal_to<SubChunkPos> >,std::allocator<std::pair<SubChunkPos const ,UpdateSubChunkBlocksPacket::BlocksChangedInfo> >,0> >::clear at 0x7FF617A6E5A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6E5DD  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Dimension::_sendBlocksChangedPackets at 0x7FF617A6DB00  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6DE60  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Dimension::tick at 0x7FF617A71020  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A71425  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<3960245817072060382,4938590944480407134>::original<void * &> at 0x7FFAF2189480  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 331 
[StackTrace] Function ???????? at 0x7FFAF21894B2  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<3960245817072060382,4938590944480407134>::_hook at 0x7FFAF2187EA0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 341 
[StackTrace] Function ???????? at 0x7FFAF2187F6D  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function Level::tick at 0x7FF617A61F30  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6212F  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerLevel::tick at 0x7FF6172CF0A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6172CF0E9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFAF2189110  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFAF2189142  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFAF21874A0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFAF2187512  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function ???????? at 0x7FFAE5F529B1  [LiteLoader.Js.dll<2.5.1.2665>]
[StackTrace] Function ???????? at 0x7FFAE4EB7E05  [LiteLoader.Lua.dll<2.5.1.2665>]
[StackTrace] Function Schedule::nextTick at 0x7FFAEB1B13A0  [LiteLoader.dll<2.5.1.2665>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAEB1B15AA  [LiteLoader.dll<2.5.1.2665>]
[StackTrace] Function GameSession::tick at 0x7FF6173CB680  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6173CB6B8  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Minecraft::update at 0x7FF6170BC130  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170BCB90  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerInstance::_update at 0x7FF6170D8240  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D833D  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF6170D6820  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D6C92  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF6170D3B80  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D3B8E  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function o_exp at 0x7FFB14A52630  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A5268A  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFB16E97960  [KERNEL32.DLL<6.2.17763.3287>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB16E97974  [KERNEL32.DLL<6.2.17763.3287>]
[StackTrace] Function RtlUserThreadStart at 0x7FFB1795A2D0  [ntdll.dll<6.2.17763.3232>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB1795A2F1  [ntdll.dll<6.2.17763.3232>]

**Comment by hhhxiao** [comment]
目测不是tr的锅，要不你把tr删了看还出这个bug吗，我觉得还是会有
有`MCTick.cpp`只是因为tr hook了整个游戏的常见更新函数，所以大量函数执行路径都会在tr里面，但是实际崩溃点和tr无关

**Comment by Chlna6666** [comment]
删了就蹦别的

**Comment by Chlna6666** [comment]
[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- C++ STL Exception detected!

[StackTrace] Function invoke_watson at 0x7FFB14A9D270  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A9D288  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFB14A9D240  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A9D25E  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function std::vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > >::~vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > > at 0x7FF61689E790  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF61689E80A  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::_Hash<std::_Umap_traits<SubChunkPos,UpdateSubChunkBlocksPacket::BlocksChangedInfo,std::_Uhash_compare<SubChunkPos,std::hash<SubChunkPos>,std::equal_to<SubChunkPos> >,std::allocator<std::pair<SubChunkPos const ,UpdateSubChunkBlocksPacket::BlocksChangedInfo> >,0> >::clear at 0x7FF617A6E5A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6E5DD  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Dimension::_sendBlocksChangedPackets at 0x7FF617A6DB00  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6DE60  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Dimension::tick at 0x7FF617A71020  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A71425  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Level::tick at 0x7FF617A61F30  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF617A6212F  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerLevel::tick at 0x7FF6172CF0A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6172CF0E9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ???????? at 0x7FFAE5F529B1  [LiteLoader.Js.dll<2.5.1.2665>]
[StackTrace] Function ???????? at 0x7FFAE4EB7E05  [LiteLoader.Lua.dll<2.5.1.2665>]
[StackTrace] Function Schedule::nextTick at 0x7FFAEB1B13A0  [LiteLoader.dll<2.5.1.2665>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAEB1B15AA  [LiteLoader.dll<2.5.1.2665>]
[StackTrace] Function GameSession::tick at 0x7FF6173CB680  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6173CB6B8  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Minecraft::update at 0x7FF6170BC130  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170BCB90  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerInstance::_update at 0x7FF6170D8240  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D833D  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF6170D6820  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D6C92  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF6170D3B80  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF6170D3B8E  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function o_exp at 0x7FFB14A52630  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB14A5268A  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFB16E97960  [KERNEL32.DLL<6.2.17763.3287>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB16E97974  [KERNEL32.DLL<6.2.17763.3287>]
[StackTrace] Function RtlUserThreadStart at 0x7FFB1795A2D0  [ntdll.dll<6.2.17763.3232>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFB1795A2F1  [ntdll.dll<6.2.17763.3232>]

**Comment by Chlna6666** [comment]
> [Crashed!] -- Unhandled Exception in -> ucrtbase.dll -- Exception Code: 0xC0000409 -- C++ STL Exception detected!
> 
> [StackTrace] Function invoke_watson at 0x7FFB14A9D270 [ucrtbase.dll<6.2.17763.1490>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFB14A9D288 [ucrtbase.dll<6.2.17763.1490>] [StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFB14A9D240 [ucrtbase.dll<6.2.17763.1490>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFB14A9D25E [ucrtbase.dll<6.2.17763.1490>] [StackTrace] Function std::vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > >::~vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > > at 0x7FF61689E790 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF61689E80A [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function std::_Hash<std::_Umap_traits<SubChunkPos,UpdateSubChunkBlocksPacket::BlocksChangedInfo,std::_Uhash_compare<SubChunkPos,std::hash,std::equal_to >,std::allocator<std::pair<SubChunkPos const ,UpdateSubChunkBlocksPacket::BlocksChangedInfo> >,0> >::clear at 0x7FF617A6E5A0 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF617A6E5DD [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function Dimension::_sendBlocksChangedPackets at 0x7FF617A6DB00 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF617A6DE60 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function Dimension::tick at 0x7FF617A71020 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF617A71425 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function Level::tick at 0x7FF617A61F30 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF617A6212F [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function ServerLevel::tick at 0x7FF6172CF0A0 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6172CF0E9 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function ???????? at 0x7FFAE5F529B1 [LiteLoader.Js.dll<2.5.1.2665>] [StackTrace] Function ???????? at 0x7FFAE4EB7E05 [LiteLoader.Lua.dll<2.5.1.2665>] [StackTrace] Function Schedule::nextTick at 0x7FFAEB1B13A0 [LiteLoader.dll<2.5.1.2665>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFAEB1B15AA [LiteLoader.dll<2.5.1.2665>] [StackTrace] Function GameSession::tick at 0x7FF6173CB680 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6173CB6B8 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function Minecraft::update at 0x7FF6170BC130 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6170BCB90 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function ServerInstance::_update at 0x7FF6170D8240 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6170D833D [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF6170D6820 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6170D6C92 [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function std:🧵:_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF6170D3B80 [bedrock_server_mod.exe<1.19.20.02>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF6170D3B8E [bedrock_server_mod.exe<1.19.20.02>] [StackTrace] Function o_exp at 0x7FFB14A52630 [ucrtbase.dll<6.2.17763.1490>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFB14A5268A [ucrtbase.dll<6.2.17763.1490>] [StackTrace] Function BaseThreadInitThunk at 0x7FFB16E97960 [KERNEL32.DLL<6.2.17763.3287>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFB16E97974 [KERNEL32.DLL<6.2.17763.3287>] [StackTrace] Function RtlUserThreadStart at 0x7FFB1795A2D0 [ntdll.dll<6.2.17763.3232>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FFB1795A2F1 [ntdll.dll<6.2.17763.3232>]
这个已经跟ll开发者提交

**Comment by hhhxiao** [comment]
那就确定和tr无关，将关闭这个issue

**Comment by Chlna6666** [comment]
> 那就确定和tr无关，将关闭这个issue

BedrockOptimizer有关
掉落物品过多导致的
