### ISSUE TITLE
共计的8次崩服日志都带trapdoor

### ISSUE THREAD

**Issue by XCLHove** [hhhxiao/trapdoor-ll#18]
### trapdoor版本号版本

0.17——1.19.20

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

服务器开服一个月，共计崩服8次，每次崩服日志都类似，在每次崩服日志的同一行我都能见到trapdoor，请问是不是traopdoor的BUG日志如下：
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function GameEventMovementTrackingSystem::_trackMovement at 0x7FF62F4919D0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F491A2D  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ??$each@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VGameEventMovementTrackingComponent@@@@@Z$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$type_list@$$V@entt@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VGameEventMovementTrackingComponent@@@EntityRegistryBase@@QEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VGameEventMovementTrackingComponent@@@@@Z@Z at 0x7FF62F491170  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F491333  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function GameEventMovementTrackingSystem::tick at 0x7FF62F4920D0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F4920EA  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_32d13dfb866b2b1150b222173a507f00>,void,ITickingSystem &,TickingSystemId>::_Do_call at 0x7FF62F3CC7C0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F3CC7D9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF62F7F7EF0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F7F8217  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function EntitySystems::tick at 0x7FF62F3CD060  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F3CD103  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::original<void * &,void * &> at 0x7FFFF40E94C0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 343 
[StackTrace] Function ???????? at 0x7FFFF40E950E  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::_hook at 0x7FFFF40E7FB0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 353 
[StackTrace] Function ???????? at 0x7FFFF40E8092  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function <lambda_b44508b61f37969cf480280e06e54415>::operator() at 0x7FF63020E290  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF63020E3E4  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Level::tickEntitySystems at 0x7FF630222E40  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF630222E7A  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Level::tick at 0x7FF630221F30  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF630222408  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerLevel::tick at 0x7FF62FA8F0A0  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62FA8F0E9  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFFF40E9110  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFFF40E9142  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFFF40E74A0  [trapdoor-0.17-1.19.20.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFFF40E7512  [trapdoor-0.17-1.19.20.02.dll]
[StackTrace] Function ???????? at 0x7FFFEEEA29B1  [LiteLoader.Js.dll<2.5.1.2665>]
[StackTrace] Function ???????? at 0x7FFFEE877E05  [LiteLoader.Lua.dll<2.5.1.2665>]
[StackTrace] Function Schedule::nextTick at 0x7FFFF5DE13A0  [LiteLoader.dll<2.5.1.2665>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFF5DE15AA  [LiteLoader.dll<2.5.1.2665>]
[StackTrace] Function GameSession::tick at 0x7FF62FB8B680  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62FB8B6B8  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function Minecraft::update at 0x7FF62F87C130  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F87CB90  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function ServerInstance::_update at 0x7FF62F898240  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F89833D  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF62F896820  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F896C92  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF62F893B80  [bedrock_server_mod.exe<1.19.20.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF62F893B8E  [bedrock_server_mod.exe<1.19.20.02>]
[StackTrace] Function o_exp at 0x7FF819F52630  [ucrtbase.dll<6.2.17763.1490>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF819F5268A  [ucrtbase.dll<6.2.17763.1490>]
[StackTrace] Function BaseThreadInitThunk at 0x7FF81C8E7960  [KERNEL32.DLL<6.2.17763.2628>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF81C8E7974  [KERNEL32.DLL<6.2.17763.2628>]
[StackTrace] Function RtlUserThreadStart at 0x7FF81D37A2D0  [ntdll.dll<6.2.17763.2628>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF81D37A2F1  [ntdll.dll<6.2.17763.2628>]

**Comment by hhhxiao** [comment]
你是不是装了我的另外一个插件be优化，如果是的话应该关了就好了，参考 #16 

因为tr hook了整个游戏的顶层常见更新函数(prof指令需要)，所以大量函数执行路径都会在tr里面，但是实际崩溃点和tr无关

**Comment by XCLHove** [comment]
> 你是不是装了我的另外一个插件be优化，如果是的话应该关了就好了，参考 #16
> 
> 因为tr hook了整个游戏的顶层常见更新函数（prof指令需要），所以大量函数执行路径都会在tr里面，但是实际崩溃点和tr无关

好的，我估计也不是tr的锅，因为有时候是有玩家进入末地就崩服，貌似是bds老bug了
