### ISSUE TITLE
保存假人背包数据的功能无法正常使用

### ISSUE THREAD

**Issue by XCLHove** [hhhxiao/trapdoor-ll#19]
### trapdoor版本号版本

0.17——1.19.20

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

保存假人背包数据的功能无法正常使用，配置"keep-sim-player-inv"无论无true或者false都无法保存假人背包数据。

**Comment by hhhxiao** [comment]
下载最新的0.17.5，还有问题就重新打开这个issue,另外可参考 #12

**Comment by XCLHove** [comment]
> 下载最新的0.17.5，还有问题就重新打开这个issue，另外可参考 #12

经过测试，背包数据依然无法保存，只能保存假人的坐标。spawn假人，丢一些物品给假人，despawn假人，再spawn假人，查背包数据没有之前丢的物品

**Comment by hhhxiao** [comment]
> 

草，我有空找下bug

**Comment by hhhxiao** [comment]
#22 试试修复后的版本 https://github.com/hhhxiao/trapdoor-ll/actions/runs/2905863227 ，如果还不能保存就重新打开这个问题并说清楚**假人是手动命令添加的还是服务器启动时自动添加的**以及给**假人扔物品时候假人是否能够自动吸收**(参考 #23 )

**Comment by XCLHove** [comment]
> #22 试试修复后的版本 https://github.com/hhhxiao/trapdoor-ll/actions/runs/2905863227 ，如果还不能保存就重新打开这个问题并说清楚**假人是手动命令添加的还是服务器启动时自动添加的**以及给**假人扔物品时候假人是否能够自动吸收**(参考 #23 )

修复过的版本正常了，没有上面的问题了，还有一个问题就是关于三叉戟的，假人扔出三叉戟，假人 手动下线/假人死亡/服务器重启/服务器崩溃 后，重新生成的同名假人，三叉戟也不会属于该假人，三叉戟 打死/打到 怪没经验也不会给重新生成的假人拉仇恨。
