### ISSUE TITLE
假人支持模拟长按左键挖掘

### ISSUE THREAD

**Issue by win-researcher** [hhhxiao/trapdoor-ll#2]
模拟长按左键挖掘指：持续破坏假人视线所指的，挖掘范围（5格）内的方块

**Comment by hhhxiao** [comment]
使用`player name destroy` 但是不传位置坐标就行，不过加了`repeat`后不能不传位置坐标了。
这是MC原版命令的问题，多个可选参数的时候前面的可选参数会自动变成必填。
后面会考虑把挖掘特定位置和视线位置的方块两个功能分开

**Comment by win-researcher** [comment]
实测执行player name destroy后，假人会破坏**执行指令的玩家**视线所指的方块，而不是**假人**视线所指的方块
并且希望可以尽快不传位置坐标传repeat

版本：[9d13913](https://github.com/hhhxiao/trapdoor-ll/commit/9d1391323eb0442f2a72fba35203bd63ef446314)

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll/commit/01b68579917e89c4dd91f95ba6cd0d42426536d6
