### ISSUE TITLE
假人在重启服务器时背包无法正常保存

### ISSUE THREAD

**Issue by Vllnghost** [hhhxiao/trapdoor-ll#20]
### trapdoor版本号版本

0.16

### LiteLoader版本

2.4.2

### BDS版本

1.19.11.01

### 发生了什么?

假人在重启服务器时背包无法正常保存

### 复现此问题的步骤

1.添加假人，给假人丢一次物品，此时sim文件夹中的假人背包文件未保存这个物品
2.再给假人丢一次物品，假人背包文件保存第一个物品
3.重启服务器
4.假人背包只有第一次丢的物品

**Comment by hhhxiao** [comment]
确认是bug

**Comment by hhhxiao** [comment]
可前往https://github.com/hhhxiao/trapdoor-ll/actions/runs/2905863227 这里下载bug修复后的版本，如果还有问题就重新打开这个issue
