### ISSUE TITLE
假人与玩家重名时玩家无法进入服务器

### ISSUE THREAD

**Issue by CleMooling** [hhhxiao/trapdoor-ll#21]
### trapdoor版本号版本

0.17-1.19.20.02

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

如题

### 复现此问题的步骤

如题

**Comment by hhhxiao** [comment]
这个不是bug，请避免使用同名玩家

**Comment by CleMooling** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CleMooling** [comment]
> 

可以加一个假人前缀吗

**Comment by hhhxiao** [comment]
自己起名字的时候注意点，不过这个功能可以考虑添加
