### ISSUE TITLE
漏斗计数器bug

### ISSUE THREAD

**Issue by Rdjxo7l** [hhhxiao/trapdoor-ll#28]
### trapdoor版本

0.16-1.19.10.03

### LiteLoaderBDS版本

2.4.2

### BDS版本

1.19.10.03

### 发生了什么?

开启漏斗计算器
漏斗是无尽漏斗
用仙人掌敲一下混凝土不显示数据

### 复现此问题的步骤

1.先开指令
2.然后扔物品
3.仙人掌敲一下方块
4.最后没有数据出来

**Comment by hhhxiao** [comment]
你把配置文件种的
```json
{
      "type": "use-on",
      "item": "cactus",
      "block": "concrete",
      "prevent": false,
      "actions": [
        "counter print {baux}"
      ]
    }
```
内的`cactus`换成其他物品的名字，然后用那个物品点击就行，现在没法用是因为和转方块冲突了

**Comment by hhhxiao** [comment]
或者等我后面修复
