### ISSUE TITLE
trapdoor-ll-0.13-1.19.10.03玩家放置方块问题

### ISSUE THREAD

**Issue by Chlna6666** [hhhxiao/trapdoor-ll#3]
往上垫方块可以把自己挤下去
旁边一直放方块，可以把自己卡到方块里
删除trapdoor就没有这些现象了
使用版本：trapdoor-ll-0.13-1.19.10.03
LL:2.4.0

**Comment by hhhxiao** [comment]
你去看看配置文件tweak内的forceplacelevel是不是0,不是的话改成0就好了，我的锅，打包的时候忘记改回来了

**Comment by Chlna6666** [comment]
现在好了，谢谢
