### ISSUE TITLE
假人重进服务之后，扔出的三叉戟不在属于他了，不能获取buff经验

### ISSUE THREAD

**Issue by huxian28** [hhhxiao/trapdoor-ll#30]
### trapdoor版本

0.17.5

### LiteLoaderBDS版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

假人扔出的三叉戟，在假人重进游戏之后，变成了无主的物品，不会获取buff

**Comment by hhhxiao** [comment]
这种严格来说不算是bug,假人是用完即无的不会留下任何痕迹，新召唤的同名假人和之前的不能算是同一个人。
而且目前暂不清楚三叉戟依靠什么来识别玩家，因此没法修。
