### ISSUE TITLE
hud show不能用

### ISSUE THREAD

**Issue by imyeeyee1** [hhhxiao/trapdoor-ll#31]
### trapdoor版本

0.18-1.19.22

### LiteLoaderBDS版本

2.6.2

### BDS版本

1.19.22

### 发生了什么?

如题所述

### 复现此问题的步骤

1.安装trapdoor
2.打/hud add mspt
3.然后打/hud show true

**Comment by imyeeyee1** [comment]
![Uploading Screenshot_2022-09-06-15-00-27-475_com.bugjang11921plus.jpg…]()

**Comment by imyeeyee1** [comment]
![Screenshot_2022-09-06-15-00-27-475_com bugjang11921plus](https://user-images.githubusercontent.com/100524318/188568105-665dcf95-92cf-4f88-bba3-0df7e6069a47.jpg)

**Comment by hhhxiao** [comment]
问你的腐竹，他把这个功能关了
