### ISSUE TITLE
spawn prob指令报出内存位置访问无效

### ISSUE THREAD

**Issue by Sy1rKimihiro** [hhhxiao/trapdoor-ll#34]
### trapdoor版本

0.17.5-1.19.20.02

### LiteLoaderBDS版本

2.5.1

### BDS版本

1.19.20.02

### 发生了什么?

在无生物可生成的坐标处输入spawn prob指令后，游戏内提示No mob to spawn；
在不可生成生物（下半砖）的坐标输入spawn prob指令后，游戏内提示No position；
可见spawn prob指令部分可用。
在可生成生物的坐标输入spawn prob指令后，游戏内无反应，在控制台报出以下错误：
14:57:32 ERROR [PreLoader] Could not find function in memory: ?_isSpawnPositionOk@Spawner@@IEBA_NAEBVMobSpawnRules@@AEAVBlockSource@@AEBVBlockPos@@_N@Z

14:57:32 ERROR [PreLoader] Plugin: trapdoor-0.17.5-1.19.20.02.dll

14:57:32 ERROR [LiteLoader] Uncaught SEH Exception Detected!

14:57:32 ERROR [LiteLoader] Error: Code [1073741819'>-1073741819] 内存位置访问无效。

14:57:32 ERROR [LiteLoader] In Function (DynamicCommand::execute)

14:57:32 ERROR [LiteLoader] In Plugin <Trapdoor>

spawn下的其它指令（analyze/count/forcesp）正常可用
trapdoor其它功能皆正常
spawn prob指令之前可用

晚于trapdoor加入的插件有：
TrustedSkin             /信任所有皮肤
DeathMessages      /控制台死亡信息显示
FackEggChange      /禁止非创造玩家修改刷怪笼
FireTransmitAttack  /火焰传递攻击
xyz                          /导航
OpManageYoyo.lxl  /OP管理
LLCheckBag             /查所有玩家背包

### 复现此问题的步骤

在可生成生物处输入/spawn prob

**Comment by hhhxiao** [comment]
收到，会近期修复

**Comment by hhhxiao** [comment]
这个在新版修了，建议更新0.18

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/commit/16f0c7f72ac50f3a9b26b267c9307540259476e3#diff-1b001bf47450287fbacfff030573026012151881817cb63c596f3b3096f02800
