### ISSUE TITLE
崩溃了

### ISSUE THREAD

**Issue by Chlna6666** [hhhxiao/trapdoor-ll#35]
### trapdoor版本

0.19.1-1.19.22.01

### LiteLoaderBDS版本

2.6.2

### BDS版本

1.19.22

### 发生了什么?

[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- C++ STL Exception detected!

[StackTrace] Function invoke_watson at 0x7FFFDA04DB80  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA04DB98  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFFDA04DB50  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA04DB6E  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function std::vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > >::~vector<std::pair<MapSample,int>,std::allocator<std::pair<MapSample,int> > > at 0x7FF765C8E790  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF765C8E80A  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function std::_Hash<std::_Umap_traits<SubChunkPos,UpdateSubChunkBlocksPacket::BlocksChangedInfo,std::_Uhash_compare<SubChunkPos,std::hash<SubChunkPos>,std::equal_to<SubChunkPos> >,std::allocator<std::pair<SubChunkPos const ,UpdateSubChunkBlocksPacket::BlocksChangedInfo> >,0> >::clear at 0x7FF766E5E1B0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E5E1ED  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Dimension::_sendBlocksChangedPackets at 0x7FF766E5D710  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E5DA70  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Dimension::tick at 0x7FF766E60C30  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E61035  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<3960245817072060382,4938590944480407134>::original<void * &> at 0x7FFFB20969A0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 333 
[StackTrace] Function ???????? at 0x7FFFB20969D2  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<3960245817072060382,4938590944480407134>::_hook at 0x7FFFB20953C0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 343 
[StackTrace] Function ???????? at 0x7FFFB209548D  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function Level::tick at 0x7FF766E51B40  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E51D3F  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ServerLevel::tick at 0x7FF7666BEE60  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7666BEEA9  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFFB2096630  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFFB2096662  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFFB20949A0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFFB2094A12  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function ???????? at 0x7FFFAC0EF691  [LiteLoader.Js.dll<2.6.2.44>]
[StackTrace] Function ???????? at 0x7FFFAB8426B1  [LiteLoader.Lua.dll<2.6.2.44>]
[StackTrace] Function Schedule::nextTick at 0x7FFFAED97440  [LiteLoader.dll<2.6.2.44>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFAED9764A  [LiteLoader.dll<2.6.2.44>]
[StackTrace] Function GameSession::tick at 0x7FF7667BB440  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7667BB478  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Minecraft::update at 0x7FF7664ABF80  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664AC9E0  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF7664C8090  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C818D  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF7664C6670  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C6AE2  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF7664C39D0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C39DE  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function o_exp at 0x7FFFDA000360  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA0003BA  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFFDCDC7E80  [KERNEL32.DLL<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDCDC7E94  [KERNEL32.DLL<6.2.17763.1>]
[StackTrace] Function RtlUserThreadStart at 0x7FFFDD2B7AB0  [ntdll.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDD2B7AD1  [ntdll.dll<6.2.17763.1>]

### 复现此问题的步骤

不确定是
std::_Hash<std::_Umap_traits<SubChunkPos,UpdateSubChunkBlocksPacket::BlocksChangedInfo,std::_Uhash_compare<SubChunkPos,std::hash<SubChunkPos>,std::equal_to<SubChunkPos> >,std::allocator<std::pair<SubChunkPos const ,UpdateSubChunkBlocksPacket::BlocksChanged
这个导致的
正常玩，无法复现
也不确定是不是BDS，自身问题
每一次的崩溃D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp
在日志中常见

**Comment by Chlna6666** [comment]
今天的又一次崩溃
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function CircuitSystem::updateBlocks at 0x7FF7671BEE70  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7671BEF77  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function LevelChunk::tick at 0x7FF7670B7900  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7670B81AA  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::original<LevelChunk * &,void * &,void * &> at 0x7FFFB20967C0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 275 
[StackTrace] Function ???????? at 0x7FFFB209682A  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::_hook at 0x7FFFB2094DF0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 290 
[StackTrace] Function ???????? at 0x7FFFB2094FB4  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActor at 0x7FF7660F87A0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7660F885E  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActorView at 0x7FF7660F8A90  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7660F8B75  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ??$each@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@@@Z$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$type_list@$$V@entt@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@EntityRegistryBase@@QEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorFlag@@@@VBlockSourceComponent@@VLoadedChunksComponent@@@@@Z@Z at 0x7FF7660F7F70  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7660F8133  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function LevelChunkTickingSystem::tick at 0x7FF7660F91E0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7660F91FA  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_32d13dfb866b2b1150b222173a507f00>,void,ITickingSystem &,TickingSystemId>::_Do_call at 0x7FF765FFC700  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF765FFC719  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF766427D70  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766428097  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function EntitySystems::tick at 0x7FF765FFCFA0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF765FFD043  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::original<void * &,void * &> at 0x7FFFB20969E0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 345 
[StackTrace] Function ???????? at 0x7FFFB2096A2E  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::_hook at 0x7FFFB20954D0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 355 
[StackTrace] Function ???????? at 0x7FFFB20955B2  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function <lambda_b44508b61f37969cf480280e06e54415>::operator() at 0x7FF766E3DEA0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E3DFF4  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Level::tickEntitySystems at 0x7FF766E52A50  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E52A8A  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Level::tick at 0x7FF766E51B40  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF766E52018  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ServerLevel::tick at 0x7FF7666BEE60  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7666BEEA9  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFFB2096630  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFFB2096662  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFFB20949A0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFFB2094A12  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function ???????? at 0x7FFFAC0EF691  [LiteLoader.Js.dll<2.6.2.44>]
[StackTrace] Function ???????? at 0x7FFFAB8426B1  [LiteLoader.Lua.dll<2.6.2.44>]
[StackTrace] Function Schedule::nextTick at 0x7FFFAED97440  [LiteLoader.dll<2.6.2.44>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFAED9764A  [LiteLoader.dll<2.6.2.44>]
[StackTrace] Function GameSession::tick at 0x7FF7667BB440  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7667BB478  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function Minecraft::update at 0x7FF7664ABF80  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664AC9E0  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF7664C8090  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C818D  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function <lambda_09545ac3fb7d475932bfc25c15253480>::operator() at 0x7FF7664C6670  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C6AE2  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_09545ac3fb7d475932bfc25c15253480> >,0> at 0x7FF7664C39D0  [bedrock_server_mod.exe<1.19.22.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7664C39DE  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function o_exp at 0x7FFFDA000360  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA0003BA  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFFDCDC7E80  [KERNEL32.DLL<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDCDC7E94  [KERNEL32.DLL<6.2.17763.1>]
[StackTrace] Function RtlUserThreadStart at 0x7FFFDD2B7AB0  [ntdll.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDD2B7AD1  [ntdll.dll<6.2.17763.1>]

**Comment by Chlna6666** [comment]
总感觉是BDS自身问题

**Comment by hhhxiao** [comment]
不是tr的锅，出现MCTick.cpp是因为这个文件hook了`serverLevel.tick`函数，只要游戏主循环内崩了都会出现这个文件

**Comment by Chlna6666** [comment]
> 不是tr的锅，出现MCTick.cpp是因为这个文件hook了`serverLevel.tick`函数，只要游戏主循环内崩了都会出现这个文件

那也就是BDS自身问题引起的tr崩溃吗？
删除tr之后崩溃的概率就小了

**Comment by Chlna6666** [comment]
> > 不是tr的锅，出现MCTick.cpp是因为这个文件hook了`serverLevel.tick`函数，只要游戏主循环内崩了都会出现这个文件
> 
> 那也就是BDS自身问题引起的tr崩溃吗？ 删除tr之后崩溃的概率就小了

        "FixBDSCrash": {
            "enabled": true
}

不知道是不是在ll打开了这个

**Comment by hhhxiao** [comment]
tr的核心代码几百年没改了，也没有动过崩溃处的任何代码。
要不你严格控制下变量，关闭其他所有插件喝相关选项，然后看看装tr和不装tr的情况，我有空也去问问ll那边。

**Comment by Chlna6666** [comment]
> tr的核心代码几百年没改了，也没有动过崩溃处的任何代码。 要不你严格控制下变量，关闭其他所有插件喝相关选项，然后看看装tr和不装tr的情况，我有空也去问问ll那边。

以前1.18也有类似的崩溃

**Comment by Chlna6666** [comment]
> > tr的核心代码几百年没改了，也没有动过崩溃处的任何代码。要不你严格控制下变量，关闭其他所有插件喝相关选项，然后看看装tr和不装tr的情况，我有空也去问问ll那边。
> 
> 以前1.18也有类似的崩溃

那个时候不装tr，人多基本不崩溃
装了之后平均一天一崩

现在四五个人在线，2到3个小时，就会有崩溃

**Comment by Chlna6666** [comment]
> tr的核心代码几百年没改了，也没有动过崩溃处的任何代码。 要不你严格控制下变量，关闭其他所有插件喝相关选项，然后看看装tr和不装tr的情况，我有空也去问问ll那边。

我主要装了
backuphelper
beopt
schedulecmd
LLAC
以及部分辅助类的LLSE
今年七月份装的tr非常的稳
但是到官方更新1.19.20以上就开始频繁崩溃

**Comment by Chlna6666** [comment]
> > tr的核心代码几百年没改了，也没有动过崩溃处的任何代码。要不你严格控制下变量，关闭其他所有插件喝相关选项，然后看看装tr和不装tr的情况，我有空也去问问ll那边。
> 
> 我主要装了 backuphelper beopt schedulecmd LLAC 以及部分辅助类的LLSE 今年七月份装的tr非常的稳 但是到官方更新1.19.20以上就开始频繁崩溃

应该全都是BDS的问题
有没有一种可能
MCTick.cpp，调用服务器内部的东西，但是服务器内部自己崩溃，但是服务器不会崩。
tr调用内部的东西，把崩溃的东西也调用了，就导致tr把服务器给崩了
只是瞎猜的。

**Comment by hhhxiao** [comment]
要不你把beopt关了试试，这东西挺不稳定的

**Comment by Chlna6666** [comment]
> 要不你把beopt关了试试，这东西挺不稳定的

我单独开beopt似乎挺稳定的
目前没有崩溃过

**Comment by Chlna6666** [comment]
> > 要不你把beopt关了试试，这东西挺不稳定的
> 
> 我单独开beopt似乎挺稳定的 目前没有崩溃过

到时候等服务器没什么人的时候再试试(移除beopt，单独加载tr)

**Comment by hhhxiao** [comment]
行吧，信息还是太少了，没法定位问题，这个issue先不关，等你后续反馈

**Comment by Chlna6666** [comment]
> 行吧，信息还是太少了，没法定位问题，这个issue先不关，等你后续反馈

我看着别人的腐竹也没什么崩溃
我自己用就天天崩溃

**Comment by Chlna6666** [comment]
[Crashed!]
-- Unhandled Exception in -> 
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function ???????? at 0x0  []

这个崩溃就更奇怪了
装了beopt

**Comment by XCLHove** [comment]
我把插件都卸载只留trapdoor崩溃就少很多了

**Comment by Chlna6666** [comment]
> 我把插件都卸载只留trapdoor崩溃就少很多了

1.19.22吗

**Comment by Chlna6666** [comment]
[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- C++ STL Exception detected!

[StackTrace] Function invoke_watson at 0x7FFFDA04DB80  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA04DB98  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFFDA04DB50  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA04DB6E  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function ???????? at 0x7FF765BF396D  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7670F73FA  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7670F83E9  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7670F8660  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7670F8784  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function IsWineEnvironment at 0x7FFFAEDB81D0  [LiteLoader.dll<2.6.2.44>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFAEDDDD22  [LiteLoader.dll<2.6.2.44>]
[StackTrace] Function ???????? at 0x7FF7668C6E19  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7665940EC  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF766599AF0  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF766E3F237  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF766E4812D  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF766E5200C  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7666BEEA9  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FFFB2096630  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 202 
[StackTrace] Function ???????? at 0x7FFFB2096662  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FFFB20949A0  [trapdoor-0.19.1-1.19.22.01.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 208 
[StackTrace] Function ???????? at 0x7FFFB2094A12  [trapdoor-0.19.1-1.19.22.01.dll]
[StackTrace] Function ???????? at 0x7FFFAB07F691  [LiteLoader.Js.dll<2.6.2.44>]
[StackTrace] Function ???????? at 0x7FFFAA0C26B1  [LiteLoader.Lua.dll<2.6.2.44>]
[StackTrace] Function Schedule::nextTick at 0x7FFFAED97440  [LiteLoader.dll<2.6.2.44>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFAED9764A  [LiteLoader.dll<2.6.2.44>]
[StackTrace] Function ???????? at 0x7FF7667BB478  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7664AC9E0  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7664C818D  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7664C6AE2  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function ???????? at 0x7FF7664C39DE  [bedrock_server_mod.exe<1.19.22.01>]
[StackTrace] Function o_exp at 0x7FFFDA000360  [ucrtbase.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDA0003BA  [ucrtbase.dll<6.2.17763.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFFDCDC7E80  [KERNEL32.DLL<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDCDC7E94  [KERNEL32.DLL<6.2.17763.1>]
[StackTrace] Function RtlUserThreadStart at 0x7FFFDD2B7AB0  [ntdll.dll<6.2.17763.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFFDD2B7AD1  [ntdll.dll<6.2.17763.1>]

新的崩溃（好像是BDS自身问题）
但移除beopt稳定了不少

**Comment by hhhxiao** [comment]
这个也应该和tr没啥关系
