### ISSUE TITLE
hsa开启后不显示

### ISSUE THREAD

**Issue by XCLHove** [hhhxiao/trapdoor-ll#36]
### trapdoor版本

0.19-1.19.22

### LiteLoaderBDS版本

2.6.1

### BDS版本

1.19.22

### 发生了什么?

hsa开启后不显示，其他功能正常，能显示

### 复现此问题的步骤

hsa show true

**Comment by hhhxiao** [comment]
装材质包了吗，就LL那个

**Comment by hhhxiao** [comment]
草，关了啊，那没事了

**Comment by XCLHove** [comment]
> 草，关了啊，那没事了

有人关了生物生成导致的
