### ISSUE TITLE
漏斗计数器在漏斗已有物品情况下会造成计数bug

### ISSUE THREAD

**Issue by Jumao15071** [hhhxiao/trapdoor-ll#38]
### trapdoor版本

0.15-1.19.30

### LiteLoaderBDS版本

2.7.0

### BDS版本

1.19.30

### 发生了什么?

漏斗计数器bug
如果漏斗里已经有了物品，使用命令/func hoppercounter true，那么已有物品会造成计数bug，每次加入新的物品都会导致计数再加入一次这些物品，即使物品已经被计算过。
![屏幕截图(1388)](https://user-images.githubusercontent.com/103634372/192965362-61bda5e9-60e3-4ad4-b864-4c18f2287ab0.png)

### 复现此问题的步骤

1.漏斗里面加入几个物品
2.使用/func hoppercounter
3./count print 打印漏斗计数数量
4.发现数量异常

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/pull/41
修好了，现在开启漏斗计数器时，漏斗内的初始物品也会被算入计数内容中，但是后面的就不会重复计算了，也修了各种数据异常和某些时候没法用的问题
