### ISSUE TITLE
LL2.4.1似乎不能用

### ISSUE THREAD

**Issue by Chlna6666** [hhhxiao/trapdoor-ll#4]
20:20:46 ERROR [LiteLoader] Fail to load plugin <trapdoor-0.13-1.19.10.03.dll>
20:20:46 ERROR [LiteLoader] Error: Code[127] The specified procedure could not be found.

**Comment by hhhxiao** [comment]
LL 2.4.1 更新修改了abi没法向前兼容，你可以
1. 退回到2.4.0
2. 等更新

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll/commit/5c36b9c6150ea4b4860989fa8499189df7f3decd 等后续release

**Comment by Chlna6666** [comment]
谢谢
