### ISSUE TITLE
添加假人服务器内存占用巨大

### ISSUE THREAD

**Issue by CreationTV** [hhhxiao/trapdoor-ll#44]
### trapdoor版本

0.19.5-1.19.30.04

### LiteLoaderBDS版本

1.19.40.02

### BDS版本

1.19.40.02

### 发生了什么?

不知道是trapdoor不适配还是什么原因，在BDS更新到1.19.40.02后，玩家输入指令：/player test spawn会让服务器瞬间及其卡顿，且服务器内存占用极大
以下是输入/player test spawn 之后Liteloader窗口的显示内容：

07:00:53 INFO [Command] <CreationTV76> /player test spawn
07:01:06 ERROR [LiteLoader] C++ Uncaught Exception Detected!
07:01:06 ERROR [LiteLoader] SEH_UNKNOW_ERROR
07:01:06 ERROR [LiteLoader] [failed to obtain stacktrace]
07:01:06 ERROR [LiteLoader] In API: PlayerClass::getRealName
07:01:06 ERROR [LiteLoader] In Plugin: BehaviorLog
07:01:06 ERROR [LiteLoader] C++ Uncaught Exception Detected!
07:01:06 ERROR [LiteLoader] SEH_UNKNOW_ERROR
07:01:06 ERROR [LiteLoader] [failed to obtain stacktrace]
07:01:06 ERROR [LiteLoader] In API: PlayerClass::setExtraData
07:01:06 ERROR [LiteLoader] In Plugin: BehaviorLog
07:01:06 INFO [Server] Player Spawned: test xuid:

本人小白，不是很懂（

**Comment by hhhxiao** [comment]
这个版本不支持1.19.40，我本地编译了一个1.19.40版本，但是LL2.8.0的SDK有点小问题，所以我暂时没有push代码，你急需的话可以加群获取，等LL那边bug修复了我再发公开release

**Comment by CreationTV** [comment]
@hhhxiao 哪里有群号(

**Comment by hhhxiao** [comment]
> @hhhxiao 哪里有群号(

https://github.com/bedrock-dev/TrapDoor 这个仓库的README

**Comment by CreationTV** [comment]
@hhhxiao 群问题答案我不会😂，还是等正式版罢

**Comment by hhhxiao** [comment]
那你等着吧

**Comment by hhhxiao** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/issues/888
等这个问题被解决就更新

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/releases/tag/0.20.0-1.19.40.02
