### ISSUE TITLE
假人缺少xuid，引起统计类插件报错。如：OnlineTimer插件

### ISSUE THREAD

**Issue by xingling2020** [hhhxiao/trapdoor-ll#46]
### trapdoor版本

0.20.0-1.19.40.02

### LiteLoaderBDS版本

2.8.1

### BDS版本

1.19.41

### 发生了什么?

假人缺少xuid，引起统计类插件报错。如：OnlineTimer插件

### 复现此问题的步骤

同时安装tr和OnlineTimer
添加假人
控制台插件报错输出

**Comment by hhhxiao** [comment]
请使用到xuid的插件自己做下判定，不要对假人做统计，假人没有xbox验证哪来的xuid
