### ISSUE TITLE
假人死亡不会自动踢出

### ISSUE THREAD

**Issue by Eric-Joker** [hhhxiao/trapdoor-ll#48]
### trapdoor版本

0.20.0-1.19.40.02

### LiteLoaderBDS版本

2.4.1

### BDS版本

1.19.41.01

### 发生了什么?

假人死亡不会自动踢出

### 复现此问题的步骤

1.召唤一个假人
2.干死他（

**Comment by hhhxiao** [comment]
怪，，最近没啥空，等有空再修

**Comment by hhhxiao** [comment]
无法复现，我自己试验可以正常退出
