### ISSUE TITLE
在1.19.50的版本中无法使用

### ISSUE THREAD

**Issue by xianshuxianshu** [hhhxiao/trapdoor-ll#50]
### trapdoor版本

trapdoor-0.20.0-1.19.40.02

### LiteLoaderBDS版本

LiteLoader-2.9.0

### BDS版本

bedrock-server-1.19.50.02

### 发生了什么?

启动bds之后显示几段红字：
19:34:39 ERROR [PreLoader] Could not find function in memory: ?getDimension@Level@@QEBAPEAVDimension@@V?$AutomaticID@VDimension@@H@@@Z
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll
19:34:39 ERROR [PreLoader] Could not find function in memory: ?getRotation@Actor@@QEBA?AVVec2@@XZ
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll
19:34:39 ERROR [PreLoader] Could not find function in memory: ??$parse@PEBVBlock@@@CommandRegistry@@AEBA_NPEAXAEBUParseToken@0@AEBVCommandOrigin@@HAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@@Z
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll

### 复现此问题的步骤

1.解压bds
2.安装LiteLoader
3.将changelog.md与README.md解压至bds根目录（或不解压），将trapdoor文件夹、trapdoor-0.20.0-1.19.40.02.dll、trapdoor-0.20.0-1.19.40.02.pdb解压至plugins
4.问题出现，且无法进入服务器，服务器
![QQ图片20221213200506](https://user-images.githubusercontent.com/103351672/207313299-500ec573-df65-4f4e-9653-843a8ed11001.png)
会不断的重启提示红字

**Comment by hhhxiao** [comment]
不支持1.19.50，等更新

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/releases/tag/0.21.0-1.19.50.2
