### ISSUE TITLE
假人进入可以悬浮的无敌状态

### ISSUE THREAD

**Issue by houzy77** [hhhxiao/trapdoor-ll#52]
### trapdoor版本

 0.21.0-1.19.50.2

### LiteLoaderBDS版本

2.9.0  64d3657 

### BDS版本

1.19.50

### 发生了什么?

假人在由主世界进入下界，再受到一次攻击后会进入可以悬浮的无敌状态
https://user-images.githubusercontent.com/121027265/208430557-9df467ba-397c-4e4b-a273-93797e7dffa6.mp4

https://user-images.githubusercontent.com/121027265/208430568-ddd908db-6d95-4836-bd3e-7d34355e5986.mp4

### 复现此问题的步骤

1.创建一个名字为中文的假人（英文没有试过,不知道会不会出问题）
2.使用/player   <name: string> moveto [vec3: x y z]，使其进入地狱门并传送到下界
3.攻击假人一下
4.假人进入无敌状态，并且不可被/player   <name: string> moveto [vec3: x y z] 指令移动

**Comment by hhhxiao** [comment]
这个是MJ的BUG,参考#23
