### ISSUE TITLE
假人无法触发烈焰人刷怪笼怪物生成，并在特定区域引发更新抑制。

### ISSUE THREAD

**Issue by Me109K4C3** [hhhxiao/trapdoor-ll#53]
### trapdoor版本

0.20.0-1.19.40.02

### LiteLoaderBDS版本

2.8.1

### BDS版本

1.19.41.01

### 发生了什么?

玩家挂机时烈焰人刷怪笼能正常工作，假人在相同位置挂机，4小时生成0只。
此外，在主世界能加载到猪人塔的某个位置生成假人，会触发更新抑制，察变成常亮，拉杆悬空不会掉落。

### 复现此问题的步骤

第一个问题让假人挂机烈焰人刷怪笼就可以复现。
第二个问题尚不清楚如何复现。

**Comment by hhhxiao** [comment]
这个区块在假人来之前是加载状态吗，必须要真人加载的时候生成假人才能正常加载区块，参考 #23

**Comment by Me109K4C3** [comment]
> 

玩家到达刷怪笼后原地放置的假人，并非将假人传送至未加载区块。

**Comment by hhhxiao** [comment]
行吧，怪

**Comment by Me109K4C3** [comment]
第二个问题的录屏如下

https://user-images.githubusercontent.com/109284866/209109514-0d3e1117-95e2-4418-852d-7182a05e98c4.mp4

**Comment by Me109K4C3** [comment]
另外此版本还存在假人死亡后无法自动退出游戏的情况，录屏如下

https://user-images.githubusercontent.com/109284866/209110793-21cac2f6-afc0-4a76-baba-a78d47332b3a.mp4

**Comment by hhhxiao** [comment]
先观望观望，我有空看看

**Comment by A-Magic-Cube** [comment]
同死亡后无法退出，而且后台报错
![1672372385885](https://user-images.githubusercontent.com/96335643/210032901-345c1f28-e674-4249-bdbf-92cfe5098db8.jpg)

**Comment by hhhxiao** [comment]
> 

你能新开个问题然后说一下复现步骤吗

**Comment by hhhxiao** [comment]
> 同死亡后无法退出，而且后台报错 ![1672372385885](https://user-images.githubusercontent.com/96335643/210032901-345c1f28-e674-4249-bdbf-92cfe5098db8.jpg)
你能新开个问题然后说一下复现步骤吗

**Comment by hhhxiao** [comment]
1. 刷怪笼无法复现，我本地测试能正常工作
2. 提供信息太少，不能确定是插件原因
