### ISSUE TITLE
服务器重启后，假人自动攻击攻击到自己身上，自残

### ISSUE THREAD

**Issue by xxxnoalter** [hhhxiao/trapdoor-ll#60]
### trapdoor版本

trapdoor-II-1.19.50.2

### LiteLoaderBDS版本

2.9.0

### BDS版本

1.19.50通1.19.51

### 发生了什么?

第一次使用假人执行攻击正常，但服务器重启后，假人判断到了自己身上（自残）

### 复现此问题的步骤

1.使用假人执行自动攻击
2.服务器重启
3.再次使用假人自动攻击
4.假人判断到假人自己身上（自残）

**Comment by hhhxiao** [comment]
你是不是指针指向了假人自己，它会攻击打指令的时候指针指向的实体，如果不指向任何实体才空挥

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/commit/0a29bd0cb5fb96fc82f6381c8f3978525801f4ae
现在禁止假人攻击自己了
