### ISSUE TITLE
prof指令后台无法正常输出

### ISSUE THREAD

**Issue by AyanMR** [hhhxiao/trapdoor-ll#63]
### trapdoor版本

0.16-1.19.10.03

### LiteLoaderBDS版本

2.4.2

### BDS版本

v1.19.11

### 发生了什么?

后台输入prof指令不会输出具体结果，仅会输出Profile Start
游戏中可正常使用
![4AXN4T~@ LRR2{W4IVRGGED](https://user-images.githubusercontent.com/56574353/210787911-005c481a-1fc1-48f5-a1a9-7c155762c540.png)

**Comment by hhhxiao** [comment]
新版没这个问题， 不会修复旧版本的bug
