### ISSUE TITLE
trapdoor假人及村民信息显示问题

### ISSUE THREAD

**Issue by Minecraft66666** [hhhxiao/trapdoor-ll#64]
### trapdoor版本

0.21.0-1.19.50.2

### LiteLoaderBDS版本

2.9.0

### BDS版本

1.19.51

### 发生了什么?

假人无法正常在地狱召唤，召唤出现在地狱对应的主世界坐标。
村民头部信息显示无法正常关闭

**Comment by hhhxiao** [comment]
假人的问题无法复现，第二个问题修了
