### ISSUE TITLE
漏斗计数器一打开就崩服

### ISSUE THREAD

**Issue by HarryMao2007** [hhhxiao/trapdoor-ll#65]
### trapdoor版本

0.21.0-1.19.50.02

### LiteLoaderBDS版本

2.9.0

### BDS版本

1.19.51

### 发生了什么?

漏斗计数器一打开就崩服

**Comment by hhhxiao** [comment]
#59
可以从action中下载未发布release的最新版本 https://github.com/bedrock-dev/trapdoor-ll/suites/10120349346/artifacts/493840138
