### ISSUE TITLE
召唤多个假人并直接tp到未加载区块时服务器崩溃

### ISSUE THREAD

**Issue by Eric-Joker** [hhhxiao/trapdoor-ll#66]
### trapdoor版本

0.21.0-1.19.50.2

### LiteLoaderBDS版本

2.9.1

### BDS版本

1.19.51.1

### 发生了什么?

使用shortcuts召唤多个假人并将他们直接tp到未加载区块时服务器崩溃，进程关闭
直接使用指令只生成一个假人且不tp不会导致崩溃
没有尝试过使用shortcuts生成多个假人但不tp会不会导致崩溃
没有尝试过使用shortcuts只生成一个假人会不会导致崩溃
服务器已经显示三个假人已经召唤成功
存档是从1.19.41升上来的
shortcuts：
`
    {
      "type": "command",
      "command": "set-players",
      "actions": [
        "player 工具人 despawn",
        "player 工具人 spawn",
        "tp 工具人 205 65 17",
        "player 刷铁机打工仔 despawn",
        "player 刷铁机打工仔 spawn",
        "tp 刷铁机打工仔 53 63 31 -90 0",
        "player 守卫者农场打工仔 despawn",
        "player 守卫者农场打工仔 spawn",
        "tp 守卫者农场打工仔 920 86 1688"
      ]
    }
`

崩溃日志：
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function WeakStorageEntity::_isSet at 0x7FF7035CA560  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7035CA573  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function StackResultStorageEntity::StackResultStorageEntity at 0x7FF70337F7E0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70337F80E  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function WeakEntityRef::tryUnwrap<Actor> at 0x7FF702FC2650  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF702FC2670  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ScriptModuleMinecraft::ScriptActorEventSignal<Scripting::TypedObjectHandle<ScriptModuleMinecraft::ScriptActorAddEffectEvent> >::dispatch at 0x7FF703DD9C90  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703DD9D07  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ScriptModuleMinecraft::ScriptWorldEventsUtils::_dispatchActorEvent<ScriptModuleMinecraft::ScriptActorAddEffectEvent & __ptr64,ScriptModuleMinecraft::ScriptActorEventSignal<Scripting::TypedObjectHandle<ScriptModuleMinecraft::ScriptActorAddEffectEvent> > & __ptr64> at 0x7FF703D7FF30  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703D80035  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ScriptModuleMinecraft::ScriptActorEventListener::onEvent at 0x7FF7041B3750  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7041B38AE  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function boost::detail::variant::invoke_visitor<boost::detail::variant::result_wrapper1<<lambda_8e29498f2384ad12e7f872ccb448c61c>,boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<boost::mpl::long_<20>,Details::ValueOrRef<ActorAcquiredItemEvent const >,boost::mpl::l_item<boost::mpl::long_<19>,Details::ValueOrRef<ActorAddEffectEvent const >,boost::mpl::l_item<boost::mpl::long_<18>,Details::ValueOrRef<ActorAnimationChangedEvent const >,boost::mpl::l_item<boost::mpl::long_<17>,Details::ValueOrRef<ActorAttackEvent const >,boost::mpl::l_item<boost::mpl::long_<16>,Details::ValueOrRef<ActorCarriedItemChangedEvent const >,boost::mpl::l_item<boost::mpl::long_<15>,Details::ValueOrRef<ActorDefinitionTriggeredEvent const >,boost::mpl::l_item<boost::mpl::long_<14>,Details::ValueOrRef<ActorDefinitionEndedEvent const >,boost::mpl::l_item<boost::mpl::long_<13>,Details::ValueOrRef<ActorDroppedItemEvent const >,boost::mpl::l_item<boost::mpl::long_<12>,Details::ValueOrRef<ActorEquippedArmorEvent const >,boost::mpl::l_item<boost::mpl::long_<11>,Details::ValueOrRef<ActorHurtEvent const >,boost::mpl::l_item<boost::mpl::long_<10>,Details::ValueOrRef<ActorKilledEvent const >,boost::mpl::l_item<boost::mpl::long_<9>,Details::ValueOrRef<ActorPlacedItemEvent const >,boost::mpl::l_item<boost::mpl::long_<8>,Details::ValueOrRef<ActorRemovedEvent const >,boost::mpl::l_item<boost::mpl::long_<7>,Details::ValueOrRef<ActorRemoveEffectEvent const >,boost::mpl::l_item<boost::mpl::long_<6>,Details::ValueOrRef<ActorUseItemEvent const >,boost::mpl::l_item<boost::mpl::long_<5>,Details::ValueOrRef<KnockBackEvent const >,boost::mpl::l_item<boost::mpl::long_<4>,Details::ValueOrRef<MountTamingEvent const >,boost::mpl::l_item<boost::mpl::long_<3>,Details::ValueOrRef<ProjectileHitEvent const >,boost::mpl::l_item<boost::mpl::long_<2>,Details::ValueOrRef<ActorGriefingBlockEvent const >,boost::mpl::l_item<boost::mpl::long_<1>,Details::ValueOrRef<ActorDefinitionStartedEvent const >,boost::mpl::l_end> >  at 0x7FF702FB1990  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF702FB1A4C  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ??@8e4da0cecf50d2e0d890895645cdd637@ at 0x7FF702FB6810  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF702FB68AD  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function EventListenerDispatcher<ActorEventListener>::onEvent at 0x7FF702FBA3E0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF702FBA446  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function <lambda_3cd48ab6e9ddfe93a3e0bdaabc8d2657>::operator()<ActorAddEffectEvent> at 0x7FF70390EE60  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70390EF06  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ??@c6f78ac7498e7657faeb865d629626c8@ at 0x7FF703915960  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7039159F6  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_a562712200e7e7f092f1b10703af7149>,enum EventResult,gsl::not_null<ActorEventListener * __ptr64> >::_Do_call at 0x7FF703916460  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7039164D9  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function EventCoordinator<ActorEventListener>::processEvent at 0x7FF7037A89E0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7037A8AEC  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ActorEventCoordinator::sendEvent at 0x7FF703917010  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703917252  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function Actor::addEffect at 0x7FF70381B3D0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70381B7A2  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function BeaconBlockActor::_applyEffects at 0x7FF7044AA580  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7044AA810  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function BeaconBlockActor::tick at 0x7FF7044AB610  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7044ABC8A  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function LevelChunk::tickBlockEntities at 0x7FF7044F3950  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7044F3CB2  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function THookTemplate<8345523433471749594,-868109241258270114>::original<void * &,void * &> at 0x7FF9D2606890  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 305 
[StackTrace] Function ???????? at 0x7FF9D26068DE  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function THookTemplate<8345523433471749594,-868109241258270114>::_hook at 0x7FF9D2605100  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 315 
[StackTrace] Function ???????? at 0x7FF9D26051DC  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function LevelChunk::tick at 0x7FF7044F2E90  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7044F37B8  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::original<LevelChunk * &,void * &,void * &> at 0x7FF9D26067C0  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 276 
[StackTrace] Function ???????? at 0x7FF9D260682A  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::_hook at 0x7FF9D2604DE0  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 291 
[StackTrace] Function ???????? at 0x7FF9D2604FA4  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActor at 0x7FF7034B51E0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7034B52AE  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActorView at 0x7FF7034B5510  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7034B55FE  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function EntityRegistryBase::View<1,EntityContext,EntityRegistry,entt::type_list<>,FlagComponent<ActorFlag>,BlockSourceComponent,LoadedChunksComponent>::each<void (__cdecl*)(ViewedEntityContextT<EntityContext,FlagComponent<ActorFlag>,BlockSourceComponent,LoadedChunksComponent> & __ptr64)> at 0x7FF7034B4A20  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7034B4BEA  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function LevelChunkTickingSystem::tick at 0x7FF7034B56F0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7034B570A  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_de46fc0e395ea1d73f8119238160f27c>,void,ITickingSystem &,TickingSystemId>::_Do_call at 0x7FF703377190  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7033771B0  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF703692420  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70369275F  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function EntitySystems::tick at 0x7FF703377AB0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703377B5C  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::original<void * &,void * &> at 0x7FF9D26069E0  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 346 
[StackTrace] Function ???????? at 0x7FF9D2606A2E  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function THookTemplate<791796048354866616,-1301571388534873506>::_hook at 0x7FF9D26054C0  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 356 
[StackTrace] Function ???????? at 0x7FF9D26055A2  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function <lambda_b44508b61f37969cf480280e06e54415>::operator() at 0x7FF704265920  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF704265A20  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function Level::tickEntitySystems at 0x7FF70427D650  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70427D68A  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function Level::tick at 0x7FF70427C6D0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70427CBD5  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ServerLevel::tick at 0x7FF7039A3500  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7039A354E  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::original<void * &> at 0x7FF9D2606630  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 203 
[StackTrace] Function ???????? at 0x7FF9D2606662  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function THookTemplate<2929696350043286095,4938590944480407134>::_hook at 0x7FF9D2604990  [trapdoor-0.21.0-1.19.50.02.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 209 
[StackTrace] Function ???????? at 0x7FF9D2604A02  [trapdoor-0.21.0-1.19.50.02.dll]
[StackTrace] Function ???????? at 0x7FF9CE55319E  [LiteLoader.Js.dll<2.9.1.0>]
[StackTrace] Function ???????? at 0x7FF9CDBB61C0  [LiteLoader.Lua.dll<2.9.1.0>]
[StackTrace] Function Schedule::nextTick at 0x7FF9CFAB62D0  [LiteLoader.dll<2.9.1.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF9CFAB64DA  [LiteLoader.dll<2.9.1.0>]
[StackTrace] Function GameSession::tick at 0x7FF703A1F120  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703A1F16A  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function Minecraft::update at 0x7FF703790E50  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703791614  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF703797270  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF70379736D  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function <lambda_9c72527c89bc5df41fe482e4153a365f>::operator() at 0x7FF703795590  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF703795A35  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_9c72527c89bc5df41fe482e4153a365f> >,0> at 0x7FF7037927D0  [bedrock_server_mod.exe<1.19.51.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7037927DE  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function recalloc at 0x7FF9ED776AF0  [ucrtbase.dll<6.2.20348.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF9ED776B4C  [ucrtbase.dll<6.2.20348.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FF9EF5C4DD0  [KERNEL32.DLL<6.2.20348.1366>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF9EF5C4DE0  [KERNEL32.DLL<6.2.20348.1366>]
[StackTrace] Function RtlUserThreadStart at 0x7FF9F003E3E0  [ntdll.dll<6.2.20348.1129>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF9F003E40B  [ntdll.dll<6.2.20348.1129>]

dmp：
[CrashDump_20230110_11-02-26.zip](https://github.com/bedrock-dev/trapdoor-ll/files/10378601/CrashDump_20230110_11-02-26.zip)

### 复现此问题的步骤

1.使用shortcuts召唤多个假人并将他们tp到未加载区块

**Comment by hhhxiao** [comment]
在未加载区块生成假人不能正常加载区块是老问题了，MJ自己的锅，参考#23，但是我没想到会崩服。后面有时间我看有没有办法防止一下

**Comment by Eric-Joker** [comment]
.41没问题，升到.51就崩服了

**Comment by hhhxiao** [comment]
本地实测没问题，估计不是tr的锅
![a](https://user-images.githubusercontent.com/33011851/211970018-93ee09f6-3614-4f22-bb58-173ab11799ef.png)
