### ISSUE TITLE
假人使用物品bug

### ISSUE THREAD

**Issue by Latenightpoet** [hhhxiao/trapdoor-ll#68]
### trapdoor版本

0.21.0-1.19.50.2

### LiteLoaderBDS版本

2.9.1

### BDS版本

1.19.50

### 发生了什么?

1.假人使用三叉戟，会复制三叉戟，使用物品不消耗。
2.假人下线后背包物品消失。
3.假人下线后再上线，他下线前投掷的三叉戟不属于他。

**Comment by hhhxiao** [comment]
假人是用后即焚的，新召唤的假人虽然同名但是已经是新玩家了，只会继承背包数据，不认主是正常现象。
