### ISSUE TITLE
一些关于指令和假人的feat

### ISSUE THREAD

**Issue by Zaitonn** [hhhxiao/trapdoor-ll#71]
### 您的建议是否与现存的某个问题相关?请描述问题?

- `hud`指令
  - add或remove的内容是否能添加一个文件保存下来
    - 平时如果遇到服务器重启都还要重新调一遍
  - show功能个人感觉有点多余
    - 原因也同上，感觉倒是可以给add和remove加个`*`或者`all`选项一次性删除所有展示的东西
- 假人相关
  - 假人自动睡觉（检测一定范围内有床自动上床）或直接像其他维度一样不计入睡觉玩家的统计
    - 目前好像只能一个一个把假人`despawn`掉才能睡，每次要睡觉都特别麻烦，而且重新去生成假人也挺麻烦的
  - 优化命令
    - 为假人添加一个编号比如`#1`、`#2`
      - 对于手机玩家每次搞假人都很麻烦，虽然已经把假人的名字尽量缩短了但还是很麻烦
      - 我个人想法是加个list，直接把假人的名字和编号一一对应
    - 物品的选择
      - 也是操作很麻烦，得去查物品id，是否可以通过获取背包后，直接选择物品栏槽位id或背包槽位id（类似于<https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/replaceitem#%E5%8F%82%E6%95%B0>）这种方式直接选取

### 您认为还缺少什么?如何解决您的问题?

见上

---

以上只是个人一点拙见，要是感觉没必要或者做不了直接`close`掉也行🙏
如果能做的话不胜感激😭😭trapdoor加油！！

**Comment by hhhxiao** [comment]
部分建议可能会采纳，需要先和别人讨论下，issue先不关了

**Comment by hhhxiao** [comment]
1. 近期会增加缓存每个玩家自己的设置的功能，重启后就能重新读取，不会重新设置了
2. `show true` 会考虑移除，`remove all`或者`add all`就不加了,因为选项比较少没必要
3. 假人就是挂机用的，平时游戏不建议开启，自动寻床不太现实(睡觉跳过假人其他插件应该能做到)
4. 假人操作问题可能会做个GUI，编号不考虑，不过建议你装一个带TAB的材质包
5. 假人物品问题会增加根据背包索引操作物品的选项

**Comment by hhhxiao** [comment]
GUI鸽了，做GUI违背初心
