### ISSUE TITLE
使用假人可以刷物品

### ISSUE THREAD

**Issue by xinchenxpc** [hhhxiao/trapdoor-ll#73]
### trapdoor版本

0.22.0-1.19.50.2

### LiteLoaderBDS版本

2.9.2

### BDS版本

1.19.51

### 发生了什么?

![Uploading 63a9be9ee7ceaaa4.jpg…]()

### 复现此问题的步骤

![63a9be9ee7ceaaa4](https://user-images.githubusercontent.com/91319471/213959956-251afef4-938c-41a9-867d-d58bf483e71d.jpg)

**Comment by hhhxiao** [comment]
草

**Comment by hhhxiao** [comment]
无法复现，你可以发个视频，直接上传或者发b站链接啥的，issue我先关了，等看到视频确认能复现了再开

**Comment by xinchenxpc** [comment]
@hhhxiao 

Uploading teat.mp4…

**Comment by xinchenxpc** [comment]
@hhhxiao [复现过程](https://b23.tv/RUV5lPU)

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/commit/78dc563c4c7ec25003119022aa3701100665a0a8 应该修了
