### ISSUE TITLE
使用tick freeze后控制台无输出

### ISSUE THREAD

**Issue by AyanMR** [hhhxiao/trapdoor-ll#75]
### trapdoor版本

trapdoor-0.22.0-1.19.50.02

### LiteLoaderBDS版本

 LiteLoaderBDS 2.9.1

### BDS版本

1.19.51.01(ProtocolVersion 560)

### 发生了什么?

使用tick freeze后控制台无输出
![3B25KMXZU(3$X_963QB1S}B](https://user-images.githubusercontent.com/56574353/214526764-5cacdb56-5ad2-4965-95d4-87beecdd62d4.png)

### 复现此问题的步骤

输入tick freeze

**Comment by hhhxiao** [comment]
主线程停止了，我后面禁止后台输入freeze
