### ISSUE TITLE
假人

### ISSUE THREAD

**Issue by imyeeyee1** [hhhxiao/trapdoor-ll#9]
为什么纸人挖方块的时候后台会写 can not write file

**Comment by imyeeyee1** [comment]
> 为什么纸人挖方块的时候后台会写 can not write file

**Comment by imyeeyee1** [comment]
我是用LL 2.4.2 最新trapdoor

**Comment by hhhxiao** [comment]
试试这个 https://github.com/hhhxiao/trapdoor-ll/actions/runs/2746283493 看看还有错误吗

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll/commit/46faf12ad18efe7a9ce77bb5f06046a06633eb24

**Comment by imyeeyee1** [comment]
那个怎么用 不会qwq

**Comment by imyeeyee1** [comment]
哦 点那个就能下了ww

**Comment by imyeeyee1** [comment]
> 试试这个 https://github.com/hhhxiao/trapdoor-ll/actions/runs/2746283493 看看还有错误吗

没有了

**Comment by hhhxiao** [comment]
最近会发个最近的release解决这个问题
