### ISSUE TITLE
疑似某些hook崩服

### ISSUE THREAD

**Issue by Milvona** [hhhxiao/trapdoor-ll#95]
### trapdoor版本

0.36.0-1.19.72.01-ab4ba2a

### LiteLoaderBDS版本

LiteLoaderBDS 2.12.3+6dd902b

### BDS版本

Version 1.19.72.01(ProtocolVersion 575)

### 发生了什么?

[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- Minidump generated in Directory ./logs/Crash

[StackTrace] Function CircuitSystem::updateBlocks at 0x7FF617DAEAD0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function LevelChunk::tick at 0x7FF617D98060  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::_hook at 0x7FFC1B0300C0  [trapdoor-0.36.0-1.19.72.01-e0cf11f.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 366
[StackTrace] Function THookTemplate<-8434186887825414863,6463148421339488862>::_hook at 0x7FFC1F601A20  [trapdoor-0.36.0-1.19.72.01-ab4ba2a.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 366
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActor at 0x7FF616B3EF20  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function LevelChunkTickingSystem::_tickLevelChunksAroundActorView at 0x7FF616B3F250  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function ViewT<EntityContext,EntityRegistry,ActorOwnerComponent,LoadedChunksComponent>::each<void (__cdecl*)(ActorOwnerComponent & __ptr64,LoadedChunksComponent & __ptr64)> at 0x7FF616B3E670  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function LevelChunkTickingSystem::tick at 0x7FF616B3F320  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function std::_Func_impl_no_alloc<<lambda_32d13dfb866b2b1150b222173a507f00>,void,ITickingSystem &,TickingSystemId>::_Do_call at 0x7FF616A1EEF0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF616BAA030  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function EntitySystems::tick at 0x7FF616A1F810  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function <lambda_b44508b61f37969cf480280e06e54415>::operator() at 0x7FF617986A90  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function Level::tickEntitySystems at 0x7FF61799C3F0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function Level::_subTick at 0x7FF61798E7D0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function ServerLevel::_subTick at 0x7FF616F38A80  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function Schedule::nextTick at 0x7FFC0FE4FE60  [LiteLoader.dll<2.12.3.0>]
[StackTrace] Function Level::tick at 0x7FF61799C1F0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function GameSession::tick at 0x7FF617899450  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function THookTemplate<-4427376470458475081,4938573352294362718>::_hook at 0x7FFC1B02FB10  [trapdoor-0.36.0-1.19.72.01-e0cf11f.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 279
[StackTrace] Function THookTemplate<-4427376470458475081,4938573352294362718>::_hook at 0x7FFC1F601470  [trapdoor-0.36.0-1.19.72.01-ab4ba2a.dll]
-- At File D:\a\trapdoor-ll\trapdoor-ll\src\functions\MCTick.cpp : Line 279
[StackTrace] Function Minecraft::update at 0x7FF61767D450  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF616EBBF10  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function <lambda_f2e707221d48fb1510572c959b70280b>::operator() at 0x7FF616EBA2D0  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_f2e707221d48fb1510572c959b70280b> >,0> at 0x7FF616EB6650  [bedrock_server_mod.exe<1.19.72.01>]
[StackTrace] Function recalloc at 0x7FFC41626AF0  [ucrtbase.dll<6.2.20348.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFC42D64EC0  [KERNEL32.DLL<6.2.20348.143>]
[StackTrace] Function RtlUserThreadStart at 0x7FFC438AE1E0  [ntdll.dll<6.2.20348.112>]

### 复现此问题的步骤

未知崩服

**Comment by hhhxiao** [comment]
应该不是tr的锅
